version: '3.8'
services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: amithsai
      POSTGRES_USER: postgres
      APP_DB_NAME: ecommerce_db_test
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  ecommerce:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
    - 8090:8090

